language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script
    script: now --public --token $NOW_TOKEN -e WEBHOOK_PROXY_URL=$WEBHOOK_PROXY_URL -e APP_ID=$APP_ID -e WEBHOOK_SECRET=$WEBHOOK_SECRET -e PRIVATE_KEY="${PRIVATE_KEY}" && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
